[features]
seeds = false

[programs.localnet]
candy_guard = "FEf9mMa22GxyxVKjXDUwdiYtH8isuhAsSqBSjQg9CTzu"
candy_machine = "EevwmjzdgWnG1Bqfthb33KEsQUmyPsoofKLdu3JJR4zS"

[programs.devnet]
candy_guard = "FEf9mMa22GxyxVKjXDUwdiYtH8isuhAsSqBSjQg9CTzu"
candy_machine = "EevwmjzdgWnG1Bqfthb33KEsQUmyPsoofKLdu3JJR4zS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/febo/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/candy-guard",
  "programs/candy-machine",
]
