name: Prepare program environment

inputs:
  rust:
    description: The Rust version to install
    required: true
  solana:
    description: The Solana version to install
    required: true
  cache:
    description: Whether we should cache files between workflow runs
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: ./.github/actions/install-rust
      with:
        version: ${{ inputs.rust }}

    - name: Install Solana
      uses: ./.github/actions/install-solana
      with:
        version: ${{ inputs.solana }}
        cache: ${{ inputs.cache }}
