name: Install Rust

inputs:
  version:
    description: The Rust version to install
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Rust
      id: rust_toolchain
      uses: actions-rs/toolchain@v2
      with:
        toolchain: ${{ inputs.version }}
        override: true
        profile: minimal
        components: rustfmt, clippy

    - name: Add Cargo bin to Path
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Rust install
      run: |
        echo "Verifying rust '${{ inputs.version }}' ..."
        rustc --version
        cargo --version
        cargo clippy --version
        rustfmt --version
      shell: bash

    - name: Share rustc hash
      run: |
        echo 'RUSTC_HASH=${{ steps.rust_toolchain.outputs.rustc_hash }}' >> $GITHUB_ENV
      shell: bash
