name: Deploy JS Client

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Version bump
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      create_release:
        description: Create a GitHub release
        required: true
        type: boolean
        default: true

env:
  CACHE: true

jobs:
  build_programs:
    name: Programs
    uses: ./.github/workflows/build-programs.yml
    secrets: inherit

  test_js:
    name: JS client
    needs: [build_programs]
    uses: ./.github/workflows/test-js.yml
    secrets: inherit

  deploy_js:
    name: Deploy JS client
    runs-on: ubuntu-latest
    needs: [test_js]
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: ./.github/actions/install-node
        with:
          version: ${{ vars.NODE_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        uses: ./.github/actions/install-js-client
        with:
          cache: ${{ env.CACHE }}

      - name: Build
        working-directory: ./clients/js
        run: pnpm build

      - name: Bump
        id: bump
        working-directory: ./clients/js
        run: |
          pnpm version ${{ github.event.inputs.bump }} --no-git-tag-version
          echo "new_version=$(pnpm pkg get version | sed 's/"//g')" >> $GITHUB_OUTPUT

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        vars:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        working-directory: ./clients/js
        run: pnpm publish --no-git-checks

      - name: Commit and tag new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy JS client v${{ steps.bump.outputs.new_version }}
          tagging_message: js@v${{ steps.bump.outputs.new_version }}

      - name: Create GitHub release
        if: github.event.inputs.create_release == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: js@v${{ steps.bump.outputs.new_version }}
