name: Dummy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true
  RUST_VERSION: 1.65.0
  SOLANA_VERSION: 1.10.34
  PROGRAMS: system-extras token-extras

jobs:
  build_programs:
    name: Build Programs
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-programs
        with:
          rust: ${{ env.RUST_VERSION }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Build programs
        run: |
          for x in ${{ env.PROGRAMS }}; do
            (cd ./programs/$x && cargo build-bpf)
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program-builds
          path: programs/**/target/deploy/*.so
