name: Dummy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true
  RUST_VERSION: 1.65.0
  SOLANA_VERSION: 1.10.34
  PROGRAMS: [system-extras, token-extras]

jobs:
  build_programs:
    name: Build Programs
    runs-on: ubuntu-latest
    steps:
      - name: Print things
        run: |
          for x in ${{ env.PROGRAMS }}; do
            echo "$x"
          done
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: ./.github/actions/install-rust
        with:
          version: ${{ env.RUST_VERSION }}
          cache: ${{ env.CACHE }}
      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}
      - name: Cache target folders
        if: env.CACHE == 'true'
        uses: actions/cache@v3
        with:
          path: ./programs/**/target/
          key: ${{ runner.os }}-programs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-programs
      - name: Build System Extras
        working-directory: ./programs/system-extras
        run: cargo build-bpf
      - name: Build Token Extras
        working-directory: ./programs/token-extras
        run: cargo build-bpf
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program-builds
          path: programs/**/target/deploy/*.so
