name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true

jobs:
  build_programs:
    name: Programs
    uses: ./.github/workflows/build-programs.yml
    secrets: inherit

  test_programs:
    name: Programs
    uses: ./.github/workflows/test-programs.yml
    secrets: inherit

  generate_clients:
    name: Clients / Generate
    runs-on: ubuntu-latest
    needs: [build_programs]
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: ./.github/actions/install-node
        with:
          version: ${{ vars.NODE_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache IDL generators
        if: env.CACHE == 'true'
        uses: actions/cache@v3
        with:
          path: ./.crates/
          key: ${{ runner.os }}-idl-generators-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-idl-generators

      - name: Generate IDLs and clients
        run: pnpm generate

      - name: Commit generated clients
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated clients

  detect_client_changes:
    name: Clients / Detect changes
    runs-on: ubuntu-latest
    needs: [generate_clients]
    outputs:
      js: ${{ steps.changes.outputs.js_client }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

  debug_changes:
    name: Clients / Debug
    runs-on: ubuntu-latest
    needs: [detect_client_changes]
    steps:
      - name: Debug
        run: |
          echo "${{ needs.detect_client_changes.outputs.js }}"

  test_js:
    if: needs.detect_client_changes.outputs.js == 'true'
    name: Clients / JS
    needs: [detect_client_changes]
    uses: ./.github/workflows/test-js.yml
    secrets: inherit
