name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_programs:
    name: Build Programs
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          version: 1.10.34
      - name: Build System Extras
        working-directory: ./programs/system-extras
        run: cargo build-bpf
      - name: Build Token Extras
        working-directory: ./programs/token-extras
        run: cargo build-bpf
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program-builds
          path: programs/**/target/deploy/*.so

  test_js:
    name: Test JS Client
    runs-on: ubuntu-latest
    needs: build_programs
    strategy:
      matrix:
        node: ["16.x", "18.x"]
        solana: ["1.10.34"]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          version: ${{ matrix.solana }}

      - name: Install Node.js
        uses: ./.github/actions/install-node
        with:
          node_version: ${{ matrix.node }}

      - name: Start local validator using Amman
        run: pnpm validator

      - name: Install dependencies
        working-directory: ./clients/js
        run: pnpm install --frozen-lockfile

      - name: Build and run tests
        working-directory: ./clients/js
        run: pnpm build && pnpm test
