name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.changes.outputs.any }}
      programs: ${{ steps.changes.outputs.programs }}
      program_matrix: ${{ steps.program_matrix.outputs.matrix }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

      - name: Get matrix of programs to test
        id: program_matrix
        env:
          PROGRAMS: ${{ vars.PROGRAMS }}
        run: |
          CHANGES=$(echo ${{ toJSON(steps.changes.outputs.changes) }})
          KEYS=$(echo $PROGRAMS | jq -c '.[]' | sed 's/"//g')
          CHANGED_KEYS=$(for key in $KEYS; do
            change_key=$(echo $key | sed 's/-/_/g' | sed 's/$/_program/')
            index=$(echo $CHANGES | jq -c ". | index(\"$change_key\")")
            if [ $(echo $index) != 'null' ]; then
              echo $key
            fi
          done)
          echo "matrix=$(echo "$CHANGED_KEYS" | jq -R . | jq -sc . | sed 's/""//')" | tee $GITHUB_OUTPUT

  build_programs:
    name: Programs
    if: ${{ needs.changes.outputs.any == 'true' }}
    needs: changes
    uses: ./.github/workflows/build-programs.yml
    secrets: inherit

  test_programs:
    name: Programs
    if: ${{ needs.changes.outputs.programs == 'true' }}
    needs: changes
    uses: ./.github/workflows/test-programs.yml
    secrets: inherit
    with:
      program_matrix: ${{ needs.changes.outputs.program_matrix }}

  generate_clients:
    name: Generate clients
    if: ${{ needs.changes.outputs.any == 'true' }}
    needs: build_programs
    runs-on: ubuntu-latest
    outputs:
      js_changed: ${{ steps.changes.outputs.js_client }}
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: ./.github/actions/install-node
        with:
          version: ${{ vars.NODE_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache IDL generators
        if: env.CACHE == 'true'
        uses: actions/cache@v3
        with:
          path: ./.crates/
          key: ${{ runner.os }}-idl-generators-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-idl-generators

      - name: Generate IDLs and clients
        run: pnpm generate

      - name: Commit generated clients
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated clients

      - name: Detect client changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

  test_js:
    if: needs.generate_clients.outputs.js_changed == 'true'
    name: JS Client
    needs: generate_clients
    uses: ./.github/workflows/test-js.yml
    secrets: inherit
