name: Verify JS client

on:
  workflow_call:
    inputs:
      solana:
        default: ${{ vars.SOLANA_VERSION }}
        type: string
      node:
        default: ${{ vars.NODE_VERSION }}
        type: string
  workflow_dispatch:
    inputs:
      solana:
        description: Solana version
        default: 1.13.6
        required: true
        type: string
      node:
        description: Node.js version
        default: 16.x
        required: true
        type: string

env:
  CACHE: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.x", "18.x"]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Start validator
        uses: ./.github/actions/start-validator
        with:
          node: ${{ matrix.node }}
          solana: ${{ inputs.solana }}
          cache: ${{ env.CACHE }}

      - name: Cache dependencies
        if: env.CACHE == 'true'
        uses: actions/cache@v3
        with:
          path: ./clients/js/node_modules/
          key: ${{ runner.os }}-clients-js-${{ hashFiles('./clients/js/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-clients-js

      - name: Install dependencies
        working-directory: ./clients/js
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ./clients/js
        run: pnpm build

      - name: Test
        working-directory: ./clients/js
        run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: ./.github/actions/install-node
        with:
          version: ${{ inputs.node }}
          cache: ${{ env.CACHE }}

      - name: Cache dependencies
        if: env.CACHE == 'true'
        uses: actions/cache@v3
        with:
          path: ./clients/js/node_modules/
          key: ${{ runner.os }}-clients-js-${{ hashFiles('./clients/js/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-clients-js

      - name: Install dependencies
        working-directory: ./clients/js
        run: pnpm install --frozen-lockfile

      - name: Format
        working-directory: ./clients/js
        run: pnpm format

      - name: Lint
        working-directory: ./clients/js
        run: pnpm lint
